/** Auto-generated by scripts/importFanzaProducts.mjs — do not edit manually. */
export interface FanzaProduct {
  contentId: string;
  title: string;
  affiliateUrl: string;
  productUrl: string;
  thumbnail?: string;
  price?: string;
  listPrice?: string;
  releaseDate?: string;
  maker?: string;
  genres: string[];
}

export const fanzaProductsImportedAt: string | null = null;

export const fanzaProducts: FanzaProduct[] = [];
