import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..");
const ENV_LOCAL_PATH = path.join(PROJECT_ROOT, ".env.local");
const OUTPUT_PATH = path.join(PROJECT_ROOT, "client", "src", "data", "fanzaProducts.ts");
const ITEM_LIST_URL = "https://api.dmm.com/affiliate/v3/ItemList";

function loadEnvLocal() {
  if (!fs.existsSync(ENV_LOCAL_PATH)) {
    throw new Error(
      ".env.local not found. Create it with DMM_API_ID and DMM_AFFILIATE_ID (see .env.example).",
    );
  }

  const env = {};
  const content = fs.readFileSync(ENV_LOCAL_PATH, "utf-8");

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const separatorIndex = trimmed.indexOf("=");
    if (separatorIndex === -1) continue;

    const key = trimmed.slice(0, separatorIndex).trim();
    let value = trimmed.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

function mapItem(item) {
  return {
    contentId: item.content_id ?? "",
    title: item.title ?? "",
    affiliateUrl: item.affiliateURL ?? "",
    productUrl: item.URL ?? "",
    thumbnail: item.imageURL?.large ?? item.imageURL?.list ?? item.imageURL?.small,
    price: item.prices?.price,
    listPrice: item.prices?.list_price,
    releaseDate: item.date,
    maker: item.iteminfo?.maker?.[0]?.name,
    genres: (item.iteminfo?.genre ?? []).map((genre) => genre.name),
  };
}

function buildItemListUrl(apiId, affiliateId) {
  const url = new URL(ITEM_LIST_URL);
  url.searchParams.set("api_id", apiId);
  url.searchParams.set("affiliate_id", affiliateId);
  url.searchParams.set("site", "FANZA");
  url.searchParams.set("service", "digital");
  url.searchParams.set("output", "json");
  url.searchParams.set("hits", "20");
  url.searchParams.set("sort", "date");
  return url;
}

function generateTypeScriptFile(products, importedAt) {
  const serializedProducts = JSON.stringify(products, null, 2);

  return `/** Auto-generated by scripts/importFanzaProducts.mjs — do not edit manually. */
export interface FanzaProduct {
  contentId: string;
  title: string;
  affiliateUrl: string;
  productUrl: string;
  thumbnail?: string;
  price?: string;
  listPrice?: string;
  releaseDate?: string;
  maker?: string;
  genres: string[];
}

export const fanzaProductsImportedAt: string | null = ${JSON.stringify(importedAt)};

export const fanzaProducts: FanzaProduct[] = ${serializedProducts};
`;
}

async function main() {
  const env = loadEnvLocal();
  const apiId = env.DMM_API_ID?.trim();
  const affiliateId = env.DMM_AFFILIATE_ID?.trim();

  if (!apiId || !affiliateId) {
    throw new Error("DMM_API_ID and DMM_AFFILIATE_ID must be set in .env.local.");
  }

  const requestUrl = buildItemListUrl(apiId, affiliateId);
  const response = await fetch(requestUrl);

  if (!response.ok) {
    throw new Error(`DMM API request failed: ${response.status} ${response.statusText}`);
  }

  const payload = await response.json();
  const items = payload?.result?.items ?? [];

  if (!Array.isArray(items)) {
    throw new Error("Unexpected DMM API response: result.items is not an array.");
  }

  const products = items.map(mapItem);
  const importedAt = new Date().toISOString();
  const output = generateTypeScriptFile(products, importedAt);

  fs.writeFileSync(OUTPUT_PATH, output, "utf-8");

  console.log(`Imported ${products.length} products to ${path.relative(PROJECT_ROOT, OUTPUT_PATH)}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
